[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "get_artifacts"
version = "0.1.0"
dependencies = [
    "click",
    "furl",
    "requests",
]

[project.scripts]
ga = "get_artifacts.__main__:get_artifacts"
