[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "job_creator"
version = "0.1.0"
dependencies = [
    "boto3",
    "click",
    "gitpython",
    "natsort",
    "requests",
    "ruamel.yaml"
]

[project.scripts]
jc = "job_creator.__main__:jc"
