---
name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-spacktainers-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: |-
          echo "Hello World!"
          ls /opt
          ls /opt/spack*
          echo "All done"
