---
name: Build Spacktainers
on: [push]
jobs:
  spacktainer-build-job:
    runs-on:
      - codebuild-spacktainers-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: configure-build-cache
        env:
          AWS_CACHE_ACCESS_KEY_ID: ${{ secrets.AWS_CACHE_ACCESS_KEY_ID }}
          AWS_CACHE_SECRET_ACCESS_KEY: ${{ secrets.AWS_CACHE_SECRET_ACCESS_KEY }}
          AWS_CACHE_BUCKET: ${{ secrets.AWS_CACHE_BUCKET }}
        run: |-
          echo "Configuring build cache"
          /opt/spack/bin/spack config blame mirrors
          /opt/spack/bin/spack mirror add --s3-access-key-id=${AWS_CACHE_ACCESS_KEY_ID} --s3-access-key-secret=${AWS_CACHE_SECRET_ACCESS_KEY} s3cache s3://${AWS_CACHE_BUCKET}
          /opt/spack/bin/spack config blame mirrors
