---
name: Build Spacktainers
on: [push]
jobs:
  spacktainer-build-job:
    runs-on:
      - codebuild-spacktainers-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: |-
          echo "Configuring build cache"
          /opt/spack/bin/spack config blame mirrors
          /opt/spack/bin/spack mirror add --s3-access-key=${AWS_CACHE_ACCESS_KEY_ID} --s3-access-key-secret=${AWS_CACHE_SECRET_ACCESS_KEY} s3cache s3://${AWS_CACHE_BUCKET}
          /opt/spack/bin/spack config blame mirrors
